### ISSUE TITLE
http://localhost:7070 Fails to start

### ISSUE THREAD

**Issue by raymondfx** [bcgov/iiwbook#59]
I am running this in Local Machine using Docker but port 7070 fails to start 
Everything else runs well
<img width="1327" alt="Screenshot 2020-07-17 at 13 15 14" src="https://user-images.githubusercontent.com/26685061/87776025-bee63f00-c82f-11ea-874c-39a8b03833cc.png">
<img width="921" alt="Screenshot 2020-07-17 at 13 17 00" src="https://user-images.githubusercontent.com/26685061/87776061-cefe1e80-c82f-11ea-885e-cbd2e3c45c8f.png">

Here is additional error on trail

```iiw-book-service_1   | ---> Migrating database ...
iiw-book-service_1   | Traceback (most recent call last):
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
iiw-book-service_1   |     (self._dns_host, self.port), self.timeout, **extra_kw)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
iiw-book-service_1   |     raise err
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
iiw-book-service_1   |     sock.connect(sa)
iiw-book-service_1   | ConnectionRefusedError: [Errno 111] Connection refused
iiw-book-service_1   | 
iiw-book-service_1   | During handling of the above exception, another exception occurred:
iiw-book-service_1   | 
iiw-book-service_1   | Traceback (most recent call last):
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
iiw-book-service_1   |     chunked=chunked)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
iiw-book-service_1   |     conn.request(method, url, **httplib_request_kw)
iiw-book-service_1   |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1254, in request
iiw-book-service_1   |     self._send_request(method, url, body, headers, encode_chunked)
iiw-book-service_1   |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
iiw-book-service_1   |     self.endheaders(body, encode_chunked=encode_chunked)
iiw-book-service_1   |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
iiw-book-service_1   |     self._send_output(message_body, encode_chunked=encode_chunked)
iiw-book-service_1   |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
iiw-book-service_1   |     self.send(msg)
iiw-book-service_1   |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 974, in send
iiw-book-service_1   |     self.connect()
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
iiw-book-service_1   |     conn = self._new_conn()
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
iiw-book-service_1   |     self, "Failed to establish a new connection: %s" % e)
iiw-book-service_1   | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7a2df0fd30>: Failed to establish a new connection: [Errno 111] Connection refused
iiw-book-service_1   | 
iiw-book-service_1   | During handling of the above exception, another exception occurred:
iiw-book-service_1   | 
iiw-book-service_1   | Traceback (most recent call last):
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
iiw-book-service_1   |     timeout=timeout
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
iiw-book-service_1   |     _stacktrace=sys.exc_info()[2])
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
iiw-book-service_1   |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
iiw-book-service_1   | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='iiw-book-agent', port=4000): Max retries exceeded with url: /schemas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a2df0fd30>: Failed to establish a new connection: [Errno 111] Connection refused',))
iiw-book-service_1   | 
iiw-book-service_1   | During handling of the above exception, another exception occurred:
iiw-book-service_1   | 
iiw-book-service_1   | Traceback (most recent call last):
iiw-book-service_1   |   File "./manage.py", line 21, in <module>
iiw-book-service_1   |     main()
iiw-book-service_1   |   File "./manage.py", line 17, in main
iiw-book-service_1   |     execute_from_command_line(sys.argv)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
iiw-book-service_1   |     utility.execute()
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
iiw-book-service_1   |     django.setup()
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
iiw-book-service_1   |     apps.populate(settings.INSTALLED_APPS)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
iiw-book-service_1   |     app_config.ready()
iiw-book-service_1   |   File "/opt/app-root/src/iiw_book/apps.py", line 31, in ready
iiw-book-service_1   |     schema_response = requests.post(f"{AGENT_URL}/schemas", json=schema_body)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 116, in post
iiw-book-service_1   |     return request('post', url, data=data, json=json, **kwargs)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 60, in request
iiw-book-service_1   |     return session.request(method=method, url=url, **kwargs)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
iiw-book-service_1   |     resp = self.send(prep, **send_kwargs)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
iiw-book-service_1   |     r = adapter.send(request, **kwargs)
iiw-book-service_1   |   File "/opt/app-root/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
iiw-book-service_1   |     raise ConnectionError(e, request=request)
iiw-book-service_1   | requests.exceptions.ConnectionError: HTTPConnectionPool(host='iiw-book-agent', port=4000): Max retries exceeded with url: /schemas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a2df0fd30>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by WadeBarnes** [comment]
It looks like the application is having issues connecting with the agent.  It's hard to tell what is going on without the full log.  However this sort of thing can happen due to startup timing, especially on initial startup.  The issue typically can be resolved by stopping and restarting the app; `./manage stop`, `./manage start`.  You want the agent to startup before the service.  I just tried it on my machine and that's exactly what happened.  The agent started after the error.

**Comment by WadeBarnes** [comment]
You can adjust the service's startup delay here; https://github.com/bcgov/iiwbook/blob/master/docker/docker-compose.yml#L60

**Comment by esune** [comment]
@WadeBarnes can we close this issue?

**Comment by raymondfx** [comment]
This issue was solved thanks @esune  @WadeBarnes
